### ISSUE TITLE
Rajasthan maps

### ISSUE THREAD

**Issue by KarthiAru** [datameet/indian_village_boundaries#11]
Hi,
Do you have the updated maps for Rajasthan?
Thanks

**Comment by tejesh0** [comment]
@KarthiAru Rajasthan village boundaries are [here ](https://github.com/tejesh95/indian_village_boundaries/tree/rajasthan)in rj folder

**Comment by KarthiAru** [comment]
@tejesh95 Thank you. Why there are multiple GeoJSON files for Rajasthan?

**Comment by tejesh0** [comment]
@karthiAru because github has 50mb file size limit
